### ISSUE TITLE
Markbot Issue and Footer Issue

### ISSUE THREAD

**Issue by skardish** [skardish/confectionery-website-prototype#2]
@thomasjbradley 
- Can't figure out why in bigger screen sizes my footer is going halfway up the page? 
- Markbot is telling me that in my html on line 74: no space between attributes, not 100% sure on what that means, was hoping you could clarify.

Thanks.

**Comment by thomasjbradley** [comment]
*Line 74:*

https://github.com/skardish/confectionery-website-prototype/blob/gh-pages/index.html#L74
There should be a space right before `src=""`

---

*Footer:*

That's a `float` clearing issue—try adding `clear: both` to the footer.
